[package]
name = "dns"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "Xous DNS resolver"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous = "0.9.33"
log-server = { package = "xous-api-log", version = "0.1.28" }
ticktimer-server = { package = "xous-api-ticktimer", version = "0.9.28" }
xous-names = { package = "xous-api-names", version = "0.9.30" }
log = "0.4.14"
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
net = {path = "../net"}
xous-ipc = "0.9.33"
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}
trng = {path = "../trng"}

utralib = { version = "0.1.13", optional = true, default-features = false }

[features]
precursor = ["utralib/precursor"]
hosted = ["utralib/hosted"]
renode = ["utralib/renode"]
default = []
