[package]
name = "codec"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "Audio CODEC server"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous = "0.9.55"
log-server = { package = "xous-api-log", version = "0.1.51" }
ticktimer-server = { package = "xous-api-ticktimer", version = "0.9.51" }
xous-names = { package = "xous-api-names", version = "0.9.53" }
log = "0.4.14"
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
susres = {package = "xous-api-susres", version = "0.9.51"}

utralib = { version = "0.1.23", optional = true, default-features = false }

[features]
precursor = ["utralib/precursor"]
hosted = ["utralib/hosted"]
renode = ["utralib/renode"]
default = []
