[package]
name = "loader"
version = "0.1.0"
authors = ["Sean Cross <sean@xobs.io>", "Foundation Devices, Inc. <hello@foundationdevices.com>"]
edition = "2018"
description = "Initial kernel loader for Xous"

[dependencies]
ed25519-dalek-loader = { path = "ed25519-dalek-loader", default-features = false, optional = true }
curve25519-dalek-loader = { path = "curve25519-dalek-loader", default-features = false, features = ["u32e_backend"], optional = true }
utralib = { version = "0.1.17", optional = true, default-features = false }
armv7 = { git = "https://github.com/Foundation-Devices/armv7.git", branch = "update", optional = true }
atsama5d27 = { git = "https://github.com/Foundation-Devices/atsama5d27.git", branch = "master", optional = true }

[dependencies.com_rs]
git = "https://github.com/betrusted-io/com_rs"
branch = "main"

[dev-dependencies]
lazy_static = "1.4.0"

[features]
precursor = ["utralib/precursor", "ed25519-dalek-loader/precursor", "curve25519-dalek-loader/precursor", "resume", "secboot"]
renode = ["utralib/renode", "ed25519-dalek-loader/renode", "curve25519-dalek-loader/renode", "resume", "secboot"]
cramium-soc = ["utralib/cramium-soc"]
cramium-fpga = ["utralib/cramium-fpga"]
atsama5d27 = ["utralib/atsama5d27", "armv7", "dep:atsama5d27"]
platform-tests = []
debug-print = []
earlyprintk = []
renode-bypass = []
secboot = []
simulation-only = []
#default = ["debug-print"]
resume = [] # suspend/resume pathway code
default = []