[package]
authors = ["bunnie <bunnie@kosagi.com>"]
description = "Xous microkernel OS inter-process name resolution server"
edition = "2018"
name = "xous-names"
version = "0.9.37"
license = "MIT OR Apache-2.0"
repository = "https://github.com/betrusted-io/xous-core/"
homepage = "https://betrusted.io/"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous-api-names = "0.9.53"
log-server = {package = "xous-api-log", version = "0.1.51"}
xous = "0.9.55"
xous-ipc = "0.9.55"
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
log = "0.4.14"
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}

utralib = {version = "0.1.23", optional = true, default-features = false }

[target.'cfg(any(windows,unix))'.dependencies]

[features]
cramium-soc = ["utralib/cramium-soc"]
cramium-fpga = ["utralib/cramium-fpga"]
precursor = ["utralib/precursor"]
hosted = ["utralib/hosted"]
renode = ["utralib/renode"]
debugprint = []
default = [] # "debugprint"
