[package]
name = "edlin"
version = "0.1.0"
authors = ["pakl <patryk@pakl.net>"]
edition = "2018"
description = "Line text editor app"

# Dependency versions enforced by Cargo.lock.
[dependencies]
log = "0.4.14"
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
xous = "0.9.47"
xous-ipc = "0.9.47"
log-server = { package = "xous-api-log", version = "0.1.43" }
ticktimer-server = { package = "xous-api-ticktimer", version = "0.9.43" }
xous-names = { package = "xous-api-names", version = "0.9.45" }
gam = {path = "../../services/gam" }
graphics-server = {path = "../../services/graphics-server" }
trng = {path = "../../services/trng"}
locales = {path = "../../locales"}
ime-plugin-api = {path = "../../services/ime-plugin-api"}
ime-plugin-shell = {path = "../../services/ime-plugin-shell"}
content-plugin-api = {path = "../../services/content-plugin-api"} # all content canvas providers must provide this API
com = {path = "../../services/com"}
llio = {path = "../../services/llio"}
codec = {path = "../../services/codec"}
cos_table = {path = "../../libs/cos_table"}
ureq = { version = "2.7.1", features = ["json"] }

[features]
default = []
