[package]
name = "vault"
version = "0.1.0"
edition = "2018"

[dependencies]
log = "0.4.14"
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
xous = "0.9.31"
xous-ipc = "0.9.31"
rkyv = {version = "0.4.3", features = ["const_generics"], default-features = false}
log-server = { package = "xous-api-log", version = "0.1.26" }
xous-names = { package = "xous-api-names", version = "0.9.28" }
gam = {path = "../../services/gam" }
graphics-server = {path = "../../services/graphics-server" }
locales = {path = "../../locales"}
tts-frontend = {path="../../services/tts"}
usb-device-xous = {path="../../services/usb-device-xous"}
usbd-human-interface-device = "0.2.1"
pddb = {path = "../../services/pddb" }
modals = {path = "../../services/modals" }
trng = {path="../../services/trng"}
susres = {package = "xous-api-susres", version = "0.9.26"}
ime-plugin-api = {path = "../../services/ime-plugin-api"}
content-plugin-api = {path = "../../services/content-plugin-api"} # all content canvas providers must provide this API
ctap-crypto = {path = "libraries/crypto"}
cbor = {path = "libraries/cbor"}
backup = {path = "libraries/backup"}
byteorder = { version = "1.4.3", default-features = false }
arrayref = "0.3.6"
subtle = { version = "2.2.3", default-features = false, features = ["nightly"] }
rand_core = "0.6.3"
ticktimer-server = {package = "xous-api-ticktimer", version = "0.9.26"}

# ux formatting
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
chrono = {version = "0.4.19", default-features = false, features = ["std"]}

# password generation
passwords = "3.1.9"

# totp
crypto-mac = "0.11.1"
sha-1 = "0.9.8"
hmac = "0.11.0"
digest = "0.9.0"
base32 = "0.4.0"
sha2 = {path="../../services/engine-sha512"}
sntpc = {version = "0.3.1"}
net = {path="../../services/net"}
com_rs-ref = {path = "../../imports/com_rs-ref"}

# performance profiling
perflib = {path="../../tools/perflib", optional = true}
utralib = {version = "0.1.13", optional = true, default-features = false }

# testing
random-pick = {version = "1.2.15", optional = true}
[dev-dependencies]
enum-iterator = "0.6.0"

[features]
precursor = []
hosted = []
renode = []
tts = []
with_ctap1 = ["ctap-crypto/with_ctap1"]
with_ctap2_1 = []
autotest = []
multireset = [] # allows credential reset more than once per boot
vaultperf = ["perflib", "xous/v2p", "utralib", "utralib/precursor"] # vault is the performance logging manager. Do not use concurrently with "shellperf", as there can only be one manager.
vault-testing = ["random-pick"]
# introduce a slight delay after UX boxes swap, in case of race conditions. Shouldn't be necessary anymore, but kept around in case there's a new edge case we missed.
ux-swap-delay = []

default = ["with_ctap1", "with_ctap2_1"] # testing removed for release tag