on:
  push:
    branches:
      - main

name: Build xous-core

jobs:
  build:
    name: Setup Rust
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: ["hosted-ci", "renode-image"]
    steps:
      - name: Install Ubuntu dependencies
        run: |
          sudo apt update
          sudo apt install -y libxkbcommon-dev

      - name: Update to latest toolchain
        run: rustup update

      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Fetch tags
        run: git fetch --prune --unshallow --tags

      - uses: Swatinem/rust-cache@v1

      - name: Install RISC-V toolkit
        run: cargo xtask install-toolkit --force --no-verify

      - name: Clean out old target directory (in case of libstd change)
        run: rm -rf target/*

      - name: Build CI targets
        run: cargo xtask ${{ matrix.task }} --no-verify
